#!/usr/bin/env bash
pactl set-sink-volume @DEFAULT_SINK@ +5%
vol=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -oP '\d+(?=%)' | head -1)
[ "$vol" -gt 100 ] && pactl set-sink-volume @DEFAULT_SINK@ 100%
